parameters:
    # Adds a fallback configuration if the env var is not set.
    env(BREVO_API_KEY):     'ThisIsSecretApiKey'
    env(BREVO_API_LIST):    'ThisIsSecretApiList'

splash:
    ################################################################################
    # List of Available Connector Connections
    ################################################################################
    connections:

        ########################################################################
        # Brevo Sandbox (Fake API for testing)
        sandbox:
            id:                 ThisIsBrevoSandboxWsId
            key:                ThisIsNotASecretKeyForBrevoSandbox
            name:               "Brevo - Sandbox"
            connector:          sendinblue
            config:
                Extended:       true
                isSandbox:      true
                WsHost:         'http://172.112.0.101'
                ApiKey:         'sandbox-api-key'
                ApiList:        '1'

        ########################################################################
        # Brevo Default (Real API)
        brevo:
            id:                 ThisIsBrevoWsId
            key:                ThisIsNotASecretKeyForBrevo
            name:               "Brevo - Staging"
            connector:          sendinblue
            config:
                Extended:       true
                ApiKey:         '%env(resolve:BREVO_API_KEY)%'
                ApiList:        '%env(resolve:BREVO_API_LIST)%'
                ApiDfCountry:   'FR'

        ########################################################################
        # Brevo Bridge Sandbox (Fake API for testing)
        bridge:
            id:                 ThisIsBrevoBridgeWsId
            key:                ThisIsNotASecretKeyForBrevoBridge
            name:               "Brevo - Bridge"
            connector:          "3.0@sendinblue"
            config:
                Extended:       true
                isSandbox:      true
                WsHost:         'http://172.112.0.101'
                ApiKey:         'sandbox-api-key'
                ApiList:        '1'



