services:
    _defaults:
        autowire:           true
        autoconfigure:      true

    ################################################################################
    # Enables Dependency Injection in Actions
    Splash\Connectors\Brevo\Actions\:
        resource: '../../Actions'
        public: true
        tags: ['controller.service_arguments']

    ################################################################################
    # Autowire for Connectors
    Splash\Connectors\Brevo\Connectors\:
        resource: '../../Connectors'

    ################################################################################
    # Autowire for Services
    Splash\Connectors\Brevo\Services\:
        resource: '../../Services'